---
abstract: 'Use pure XHTML/XML as a template'
author:
  - 'Naoki Tomita <tomita@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Semantic
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Filter::Util::Call: 0
  HTML::Selector::XPath: 0
  Scalar::Util: 1.19
  XML::LibXML: 1.69
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tomi-ru/Template-Semantic.git
version: 0.01
